In [1]:
from imports import *
import prepare as prep

pd.set_option("display.max_columns", None)

In [2]:
from pandas_profiling import ProfileReport
from pydataset import data
df = data('tips')
profile=ProfileReport(df)
profile

ModuleNotFoundError: No module named 'pandas_profiling'

[![Email](https://img.shields.io/badge/Gmail-EA4335?style=for-the-badge&logo=Gmail&logoColor=white)](foresthensley@gmail.com)

foresthensley@gmail.com

[![Linkedin](https://img.shields.io/badge/Linkedin-0A66C2?style=for-the-badge&logo=Linkedin&logoColor=white)](https://www.linkedin.com/in/forest-hensley-5389a889/)

In [14]:
y=[1 for x in range(0,100)]

In [16]:
sum([0 if  else 1 for i in y])

0

$Classificaion Project$

In [ ]:
index = ['Jack_a','Survivor_a']
col = ['Jack_p','Survivor_p' ]
pd.DataFrame(confusion_matrix(y_train, y_pred), index=[str(i) for i in titanic_clf.classes_], columns=col)

Jack_p  Survivor_p
0     300          29
1      54         151

In [ ]:
pd.DataFrame([['true negative', 'false positive'],['false negative', 'true positive']], columns=['predict_death', 'predict_survive'], index=['actual_death', 'actual_survive'])


predict_death predict_survive
actual_death     true negative  false positive
actual_survive  false negative   true positive

In [ ]:
clf = DecisionTreeClassifier(max_depth=3, random_state=123)
clf=clf.fit(X_train, y_train)

In [ ]:
clf.classes_

array([0, 1])

In [2]:
df = pd.DataFrame({
    'actual': ['c','b','b'],
    'prediction': ['c','b','b'],
})
df

actual prediction
0      c          c
1      b          b
2      b          b

In [3]:
conf=confusion_matrix(df.actual, df.prediction)
conf


array([[2, 0],
       [0, 1]])

In [4]:
conf[0][1]

0

In [5]:
x=8*10**4

a=x-.2*x

b=.2*x

c=b-.3*b

d=b*.3

x,a,b,c,d

(80000, 64000.0, 16000.0, 11200.0, 4800.0)

### iPhone
- TP - unlock stakeholder
- FP - unlock hacker
- FN - locked stakeholder
- TN - locked hacker



### iPhone
- positive case: unlock correct face
- negative case: unlock wrong face
- TP - unlock stakeholder ; cost - happy stakeholder
- FP - lock correct face ; cost - unhappy stakeholder
- TN - unlock hacker ; cost - unhappy hacker
- FN - lock hacker ; cost - happy hacker
- precision

### Spam
- positive case: put junk mail in spam folder 
- negative case: put important mail in spame folder
- TP - junk in spam
- TN - mail in inbox
- FP - mail in spam
- FN - junk in inbox

# Train, Validate, Test Split

## sk.train_test_split

In [6]:
# train, test = train_test_split(df, test_size=.2, random_state=123, stratify=df.organize_data_by_this_column)
# train, validate = train_test_split(train, test_size=.3, random_state=123, stratify=train.survived)

# Impute

## 1. Create the imputer object:

In [7]:
# imputer = sk.SimpleImputer(missing_values = None, strategy='most_frequent')

# strategies: mean, median, most_frequent

## 2. Fit to train:

In [8]:
# imputer = sk.imputer.fit(train[['column_to_fit']])

## 3. Transform data:

In [9]:
# train[['column_to_impute']] = sk.imputer.transform(train[['column_to_impute']])

In [10]:
randorr=np.random.randint(0,99,1)
randorr

array([66])